ostbuild-qemu-pull-deploy: Make a bootable image
Images made with this simple script can now be booted and used.

diff --git a/src/ostbuild/ostbuild-qemu-pull-deploy b/src/ostbuild/ostbuild-qemu-pull-deploy
--- a/src/ostbuild/ostbuild-qemu-pull-deploy
+++ b/src/ostbuild/ostbuild-qemu-pull-deploy
@@ -32,30 +32,79 @@ test -n "$target" || (echo 1>&2 "usage: $0: SRCREPO OSNAME TARGET"; exit 1)
     
 qemu_path=ostree-qemu.img
 mountpoint=ostree-qemu-mnt
+imgsize=1G
+
+function run_guestfish() {
+    guestfish -a ${qemu_path} --rw $*
+}
+
+function abort() {
+    umount ${mountpoint} 2>/dev/null
+    exit 1
+}
 
 mkdir -p ${mountpoint}
 
 if ! test -f ${qemu_path}; then
     tmppath=${qemu_path}.tmp
     rm -f ${tmppath}
-    qemu-img create ${tmppath} 8G
+    qemu-img create ${tmppath} ${imgsize}
     mkfs.ext4 -q -F ${tmppath}
 
     umount ${mountpoint} 2>/dev/null || true
     mount -o loop ${tmppath} ${mountpoint}
-    ostree admin init-fs ${mountpoint} || (umount ${mountpoint} 2>/dev/null; exit 1)
+    ostree admin init-fs ${mountpoint} || abort
     umount ${mountpoint}
     mv ${tmppath} ${qemu_path}
 fi
 
 ostreedir=${mountpoint}/ostree
 repopath=${ostreedir}/repo
+bootdir=${mountpoint}/boot
 
 mount -o loop ${qemu_path} ${mountpoint}
 
-ostree admin --ostree-dir=${ostreedir} os-init ${osname} || (umount ${mountpoint} 2>/dev/null; exit 1)
-ostree --repo=${repopath} pull-local ${srcrepo} ${target} || (umount ${mountpoint} 2>/dev/null; exit 1)
-ostree admin --ostree-dir=${ostreedir} deploy --no-kernel ${osname} ${target} || (umount ${mountpoint} 2>/dev/null; exit 1)
-ostree admin --ostree-dir=${ostreedir} prune ${osname} ${target} || (umount ${mountpoint} 2>/dev/null; exit 1)
+ostree admin --ostree-dir=${ostreedir} os-init ${osname} || abort
+ostree --repo=${repopath} pull-local ${srcrepo} ${target} || abort
+ostree admin --ostree-dir=${ostreedir} deploy --no-kernel ${osname} ${target} || abort
+ostree admin --ostree-dir=${ostreedir} --boot-dir=${bootdir} update-kernel --no-bootloader ${osname} || abort
+ostree admin --ostree-dir=${ostreedir} prune ${osname} ${target} || abort
+
+cat >${ostreedir}/deploy/${osname}/current-etc/fstab <<EOF
+/dev/sda / ext4 defautls 1 1
+EOF
+
+kernel=$(find ${bootdir} -type f -name "vmlinuz-*" -print -quit | sed -e "s,${mountpoint},,g")
+initramfs=$(find ${bootdir} -type f -name "initramfs-*.img" -print -quit | sed -e "s,${mountpoint},,g")
+
+if [ ! -f ${mountpoint}${kernel} ]; then
+    echo "No kernel found, aborting..."
+    abort
+fi
+
+if [ ! -f ${mountpoint}${initramfs} ]; then
+    echo "No initramfs found, aborting..."
+    abort
+fi
+
+mkdir -p ${bootdir}/grub
+#GRUB_PREFIX=${bootdir}/grub grub-mkconfig -o ${bootdir}/grub/grub.cfg
+cat >${bootdir}/grub/menu.lst <<EOF
+default=0
+timeout=5
+title ${osname}
+root (hd0)
+kernel ${kernel} root=/dev/sda ostree=${osname}/current
+initrd ${initramfs}
+EOF
+grub-menulst2cfg ${bootdir}/grub/menu.lst ${bootdir}/grub/grub.cfg
+cat ${bootdir}/grub/grub.cfg
+rm -f ${bootdir}/grub/menu.lst
+
+cat >${bootdir}/grub/device.map <<EOF
+(hd0) /dev/loop0
+EOF
+
+grub-install -f --boot-directory=${bootdir} '(hd0)' || abort
 
 umount ${mountpoint}
